# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations

import sqlite3
import time
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime
from difflib import SequenceMatcher
from typing import Any, Dict, List, Optional, Tuple

import streamlit as st


# ----------------------------
# Page config
# ----------------------------
st.set_page_config(page_title="🏢 Office Helpdesk Buddy", page_icon="🛠️", layout="centered")


# ----------------------------
# Playful theme CSS (single-file)
# ----------------------------
def inject_css(theme: str) -> None:
    is_neon = theme == "Neon Pop"
    accent = "#86BC25" if not is_neon else "#33CCFF"
    accent2 = "#007CB0" if not is_neon else "#DA291C"
    accent3 = "#FFD100" if not is_neon else "#86BC25"

    st.markdown(
        f"""
<style>
/* Code Generated by Sidekick is for learning and experimentation purposes only. */
:root {{
  --accent: {accent};
  --accent2: {accent2};
  --accent3: {accent3};
  --ink: #0b1220;
  --muted: #6B7280;
  --card: rgba(255,255,255,0.72);
  --stroke: rgba(17,24,39,0.08);
  --shadow: 0 14px 40px rgba(0,0,0,0.10);
}}

/* Soft gradient background */
.stApp {{
  background:
    radial-gradient(1200px 600px at 20% 10%, rgba(134,188,37,0.22), transparent 60%),
    radial-gradient(900px 500px at 85% 0%, rgba(0,124,176,0.18), transparent 55%),
    radial-gradient(900px 600px at 65% 85%, rgba(255,209,0,0.16), transparent 60%),
    linear-gradient(180deg, rgba(255,255,255,0.88), rgba(255,255,255,0.96));
}}

/* Layout spacing */
.block-container {{
  padding-top: 1.1rem;
  padding-bottom: 2rem;
  max-width: 980px;
}}

/* Hero card */
.hero {{
  border: 1px solid var(--stroke);
  background: var(--card);
  border-radius: 18px;
  padding: 1.05rem 1.1rem;
  box-shadow: var(--shadow);
  position: relative;
  overflow: hidden;
}}
.hero::before {{
  content: "";
  position: absolute;
  inset: -2px;
  background: linear-gradient(120deg, rgba(134,188,37,0.25), rgba(0,124,176,0.20), rgba(255,209,0,0.20));
  filter: blur(18px);
  opacity: 0.85;
  z-index: 0;
}}
.hero > * {{ position: relative; z-index: 1; }}

.badge {{
  display: inline-flex;
  align-items: center;
  gap: .4rem;
  padding: .25rem .55rem;
  border-radius: 999px;
  border: 1px solid var(--stroke);
  background: rgba(255,255,255,0.75);
  font-size: 0.85rem;
  color: var(--ink);
}}

.small-muted {{
  color: var(--muted);
  font-size: 0.92rem;
}}

/* Fun button feel */
div.stButton > button[kind="primary"] {{
  background: linear-gradient(135deg, var(--accent), var(--accent2));
  border: 1px solid rgba(0,0,0,.06);
  color: #07111f;
  font-weight: 800;
  border-radius: 14px;
  padding: .72rem 1rem;
  transition: transform 160ms ease, box-shadow 160ms ease, filter 160ms ease;
}}
div.stButton > button[kind="primary"]:hover {{
  transform: translateY(-1px);
  box-shadow: 0 14px 24px rgba(0,0,0,.14);
  filter: brightness(1.02);
}}
div.stButton > button[kind="primary"]:active {{
  transform: translateY(0px) scale(0.99);
}}

.quickchip {{
  border: 1px solid var(--stroke);
  background: rgba(255,255,255,0.75);
  border-radius: 14px;
  padding: .55rem .75rem;
}}

.card {{
  border: 1px solid var(--stroke);
  background: rgba(255,255,255,0.78);
  border-radius: 16px;
  padding: .9rem 1rem;
  box-shadow: 0 10px 26px rgba(0,0,0,0.06);
}}

/* Chat bubble polish */
[data-testid="stChatMessage"] {{
  border-radius: 18px;
}}
[data-testid="stChatMessage"] > div {{
  border-radius: 18px;
}}

/* Reduced motion */
@media (prefers-reduced-motion: reduce) {{
  * {{ transition: none !important; animation: none !important; }}
}}
</style>
""",
        unsafe_allow_html=True,
    )


# ----------------------------
# Data model
# ----------------------------
@dataclass
class Ticket:
    ticket_id: str
    created_at: str
    category: str
    urgency: str
    summary: str
    status: str
    mood: str  # playful: “Calm”, “Stressed”, etc.


def now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def new_ticket_id() -> str:
    return f"HD-{uuid.uuid4().hex[:8].upper()}"


# ----------------------------
# SQLite persistence (masters-level but simple)
# ----------------------------
DB_PATH = "helpdesk.db"


def db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS tickets (
          ticket_id TEXT PRIMARY KEY,
          created_at TEXT NOT NULL,
          category TEXT NOT NULL,
          urgency TEXT NOT NULL,
          summary TEXT NOT NULL,
          status TEXT NOT NULL,
          mood TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS metrics (
          key TEXT PRIMARY KEY,
          value INTEGER NOT NULL
        )
        """
    )
    conn.commit()
    return conn


def metric_bump(key: str, delta: int = 1) -> None:
    conn = db()
    cur = conn.cursor()
    cur.execute("SELECT value FROM metrics WHERE key=?", (key,))
    row = cur.fetchone()
    if row is None:
        cur.execute("INSERT INTO metrics(key, value) VALUES(?, ?)", (key, delta))
    else:
        cur.execute("UPDATE metrics SET value=? WHERE key=?", (row[0] + delta, key))
    conn.commit()


def metric_get(key: str) -> int:
    conn = db()
    cur = conn.cursor()
    cur.execute("SELECT value FROM metrics WHERE key=?", (key,))
    row = cur.fetchone()
    return int(row[0]) if row else 0


def ticket_insert(t: Ticket) -> None:
    conn = db()
    conn.execute(
        """
        INSERT OR REPLACE INTO tickets(ticket_id, created_at, category, urgency, summary, status, mood)
        VALUES(?, ?, ?, ?, ?, ?, ?)
        """,
        (t.ticket_id, t.created_at, t.category, t.urgency, t.summary, t.status, t.mood),
    )
    conn.commit()


def tickets_list(limit: int = 50) -> List[Ticket]:
    conn = db()
    cur = conn.cursor()
    cur.execute(
        "SELECT ticket_id, created_at, category, urgency, summary, status, mood FROM tickets ORDER BY created_at DESC LIMIT ?",
        (limit,),
    )
    rows = cur.fetchall()
    return [Ticket(*row) for row in rows]


def ticket_update_status(ticket_id: str, status: str) -> None:
    conn = db()
    conn.execute("UPDATE tickets SET status=? WHERE ticket_id=?", (status, ticket_id))
    conn.commit()


# ----------------------------
# “Knowledge base” (local)
# ----------------------------
KB: Dict[str, Dict[str, Any]] = {
    "Password reset": {
        "tags": ["password", "locked", "lockout", "login", "reset"],
        "steps": [
            "Try self‑service reset (if your org has one).",
            "Wait 10–15 minutes after repeated failed logins.",
            "If compromise suspected, reset from a trusted device and notify IT/Sec.",
        ],
    },
    "MFA / 2FA trouble": {
        "tags": ["mfa", "2fa", "authenticator", "otp", "push", "code"],
        "steps": [
            "Check phone date/time settings (time drift breaks MFA).",
            "Switch method (push → code / SMS → authenticator).",
            "If new phone, request MFA re‑enrollment.",
        ],
    },
    "VPN not connecting": {
        "tags": ["vpn", "anyconnect", "globalprotect", "tunnel", "error 809", "timeout"],
        "steps": [
            "Confirm basic internet works (open 2 different sites).",
            "Restart VPN client, then sign in again.",
            "If hotspot works but Wi‑Fi fails, it’s likely a network path issue.",
        ],
    },
    "Wi‑Fi issues": {
        "tags": ["wifi", "wi-fi", "wireless", "ssid", "disconnect"],
        "steps": [
            "Forget network → rejoin → re-enter credentials.",
            "Confirm you’re not on guest Wi‑Fi for corporate resources.",
            "If only one area is affected, check for local maintenance/outage.",
        ],
    },
    "Install software": {
        "tags": ["install", "software", "app", "license", "admin", "permissions"],
        "steps": [
            "Check your software portal first (approved apps).",
            "If not listed, raise an install request with justification.",
            "Provide app name, version, deadline, and whether it’s client-required.",
        ],
    },
    "Printer problems": {
        "tags": ["printer", "print", "spool", "queue", "paper jam"],
        "steps": [
            "Power-cycle printer + laptop, then retry.",
            "If secure print, confirm badge/PIN is active.",
            "Re-add the printer if it shows ‘offline’.",
        ],
    },
    "Report phishing": {
        "tags": ["phish", "phishing", "suspicious email", "spam", "link"],
        "steps": [
            "Don’t click links or open attachments.",
            "Report via your phishing button/workflow.",
            "If you entered credentials, change password immediately and notify IT/Sec.",
        ],
    },
}


def best_kb_match(query: str) -> Tuple[str, float]:
    q = query.lower().strip()
    best_title, best_score = "Install software", 0.0
    for title, entry in KB.items():
        hay = " ".join([title] + entry.get("tags", []))
        score = SequenceMatcher(None, q, hay.lower()).ratio()
        if score > best_score:
            best_title, best_score = title, score
    return best_title, best_score


def classify_category(text: str) -> str:
    title, score = best_kb_match(text)
    return title if score >= 0.20 else "General help"


# ----------------------------
# Session state
# ----------------------------
def ensure_state() -> None:
    if "theme" not in st.session_state:
        st.session_state.theme = "Playful Pastel"
    if "profile" not in st.session_state:
        st.session_state.profile = {"name": "", "device": "", "os": "", "location": ""}
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {
                "role": "assistant",
                "content": (
                    "Hey! I’m your **Office Helpdesk Buddy** 🛠️\n\n"
                    "Pick a quick button, or describe the issue in one sentence. "
                    "If we can’t fix it fast, I’ll create a ticket with the right details."
                ),
            }
        ]


ensure_state()
inject_css(st.session_state.theme)


# ----------------------------
# Sidebar (simple + cute)
# ----------------------------
with st.sidebar:
    st.markdown("### 🎛️ Control Panel")
    st.session_state.theme = st.selectbox("Theme", ["Playful Pastel", "Neon Pop"], index=0 if st.session_state.theme == "Playful Pastel" else 1)

    st.markdown("---")
    st.markdown("### 👤 Your context (optional)")
    st.session_state.profile["name"] = st.text_input("Name", value=st.session_state.profile["name"], placeholder="e.g., Asha")
    st.session_state.profile["device"] = st.text_input("Device", value=st.session_state.profile["device"], placeholder="e.g., Dell 7420")
    st.session_state.profile["os"] = st.selectbox("OS", ["", "Windows", "macOS", "Linux", "iOS", "Android"], index=0)
    st.session_state.profile["location"] = st.text_input("Location", value=st.session_state.profile["location"], placeholder="e.g., NYC 30 Rock")

    st.markdown("---")
    st.markdown("### 📈 Mini-metrics")
    st.metric("Issues resolved (self-serve)", metric_get("contained"))
    st.metric("Escalations (tickets created)", metric_get("escalated"))

    st.markdown("---")
    if st.button("🧹 Clear chat", use_container_width=True):
        st.session_state.messages = st.session_state.messages[:1]
        st.toast("Fresh slate!", icon="🧽")
        st.rerun()


# ----------------------------
# Hero header
# ----------------------------
name = st.session_state.profile.get("name") or "friend"
st.markdown(
    f"""
<div class="hero">
  <div class="badge">🏢 <b>Office Helpdesk</b> • No API Key • Local tickets (SQLite)</div>
  <h2 style="margin: .6rem 0 .2rem 0;">Welcome, {name} 👋</h2>
  <div class="small-muted">
    Quick fixes first. If it’s messy, we’ll file a ticket with the right details—without drama.
  </div>
</div>
""",
    unsafe_allow_html=True,
)

st.write("")


# ----------------------------
# Tabs: Chat / Knowledge / Tickets
# ----------------------------
tab_chat, tab_kb, tab_tickets = st.tabs(["💬 Chat", "📚 Knowledge", "🎫 Tickets"])


def assistant_typing(delay_s: float = 0.20) -> None:
    with st.chat_message("assistant"):
        ph = st.empty()
        for dots in ["", ".", "..", "..."]:
            ph.markdown(f"Thinking{dots}")
            time.sleep(delay_s)
        ph.empty()


def kb_answer(title: str) -> str:
    steps = KB[title]["steps"]
    return "Try this:\n" + "\n".join([f"{i+1}. {s}" for i, s in enumerate(steps)])


def context_line() -> str:
    p = st.session_state.profile
    bits = []
    if p.get("device"):
        bits.append(f"Device: {p['device']}")
    if p.get("os"):
        bits.append(f"OS: {p['os']}")
    if p.get("location"):
        bits.append(f"Location: {p['location']}")
    return (" | ".join(bits)) if bits else ""


def run_quick_check(kind: str) -> List[str]:
    # A tiny “wizard” with progress for masters-level UX (still no external calls)
    checks: List[Tuple[str, float]] = []
    if kind == "VPN":
        checks = [("Checking internet reachability", 0.28), ("Checking VPN client status", 0.33), ("Checking common fixes", 0.39)]
    elif kind == "Wi‑Fi":
        checks = [("Checking adapter state", 0.30), ("Checking SSID / captive portal hints", 0.33), ("Checking quick remediations", 0.37)]
    elif kind == "Login":
        checks = [("Checking lockout pattern", 0.34), ("Checking MFA hints", 0.33), ("Checking safe next steps", 0.33)]
    else:
        checks = [("Checking basics", 0.40), ("Finding likely category", 0.30), ("Preparing next steps", 0.30)]

    notes: List[str] = []
    prog = st.progress(0, text="Running quick check…")
    acc = 0.0
    for label, w in checks:
        time.sleep(0.35)
        acc += w
        prog.progress(min(int(acc * 100), 100), text=label)
        notes.append(f"✅ {label}")
    time.sleep(0.2)
    prog.empty()
    return notes


def create_ticket_from_text(user_text: str, urgency: str, mood: str) -> Ticket:
    category = classify_category(user_text)
    ctx = context_line()
    summary = user_text.strip()
    if ctx:
        summary = f"{summary} | {ctx}"
    t = Ticket(
        ticket_id=new_ticket_id(),
        created_at=now_str(),
        category=category,
        urgency=urgency,
        summary=summary[:400],
        status="Open",
        mood=mood,
    )
    ticket_insert(t)
    metric_bump("escalated", 1)
    return t


def try_contain(user_text: str) -> Tuple[bool, str]:
    title, score = best_kb_match(user_text)
    if score >= 0.28:
        msg = kb_answer(title) + "\n\nIf that doesn’t work, type **create ticket**."
        return True, msg
    return False, (
        "Tell me:\n"
        "1) What you were trying to do\n"
        "2) Exact error text (copy/paste)\n"
        "3) Urgency (low/med/high)\n\n"
        "Or type **create ticket** and I’ll file it."
    )


# ----------------------------
# TAB: Knowledge (search + cards)
# ----------------------------
with tab_kb:
    st.markdown("#### 🔎 Search the mini knowledge base")
    q = st.text_input("Search", placeholder="e.g., VPN error 809, password locked out, install app…")
    if q.strip():
        title, score = best_kb_match(q)
        st.markdown(f"<div class='card'><b>Best match:</b> {title} <span class='small-muted'>(match {int(score*100)}%)</span><br><br>{kb_answer(title).replace(chr(10), '<br>')}</div>", unsafe_allow_html=True)
        st.write("")
    st.markdown("#### 🧩 Popular fixes")
    cols = st.columns(3)
    popular = list(KB.keys())[:6]
    for i, t in enumerate(popular):
        with cols[i % 3]:
            if st.button(f"✨ {t}", use_container_width=True):
                st.session_state.messages.append({"role": "user", "content": f"[KB] {t}"})
                st.session_state.messages.append({"role": "assistant", "content": kb_answer(t) + "\n\nWant me to create a ticket if it fails?"})
                st.toast("Dropped into chat!", icon="💬")
                st.rerun()


# ----------------------------
# TAB: Tickets (list + update)
# ----------------------------
with tab_tickets:
    st.markdown("#### 🎫 Your tickets (local)")
    data = tickets_list(limit=50)
    if not data:
        st.info("No tickets yet. Create one from the chat tab.")
    else:
        for t in data[:12]:
            st.markdown(
                f"""
<div class="card">
  <div style="display:flex; justify-content:space-between; gap:12px; align-items:center;">
    <div><b>{t.ticket_id}</b> <span class="small-muted">• {t.created_at}</span></div>
    <div class="badge">Status: <b>{t.status}</b></div>
  </div>
  <div class="small-muted" style="margin-top:.25rem;">{t.category} • Urgency: {t.urgency} • Mood: {t.mood}</div>
  <div style="margin-top:.55rem;">{t.summary}</div>
</div>
""",
                unsafe_allow_html=True,
            )
            st.write("")

        st.markdown("#### 🛠️ Update a ticket status")
        pick = st.selectbox("Ticket", [t.ticket_id for t in data], index=0)
        new_status = st.selectbox("New status", ["Open", "In Progress", "Waiting on User", "Resolved"], index=0)
        if st.button("Update status", type="primary"):
            ticket_update_status(pick, new_status)
            st.toast(f"{pick} → {new_status}", icon="✅")
            st.rerun()


# ----------------------------
# TAB: Chat (quick actions + chat)
# ----------------------------
with tab_chat:
    st.markdown("<div class='small-muted'>Quick actions</div>", unsafe_allow_html=True)
    a1, a2, a3, a4 = st.columns(4)
    quick = [
        ("🔐 Login", "Login"),
        ("🛡️ VPN", "VPN"),
        ("📶 Wi‑Fi", "Wi‑Fi"),
        ("🧩 Software", "Software"),
    ]
    clicked = None
    for (label, kind), col in zip(quick, [a1, a2, a3, a4]):
        if col.button(label, use_container_width=True):
            clicked = kind

    if clicked:
        st.session_state.messages.append({"role": "user", "content": f"[Quick check] {clicked}"})
        with st.chat_message("assistant"):
            st.markdown(f"Got it. Running a quick **{clicked}** check…")
            notes = run_quick_check(clicked)
            st.markdown("\n".join(notes))
            if clicked == "VPN":
                st.markdown(kb_answer("VPN not connecting"))
            elif clicked == "Wi‑Fi":
                st.markdown(kb_answer("Wi‑Fi issues"))
            elif clicked == "Login":
                st.markdown(kb_answer("MFA / 2FA trouble") + "\n\n" + kb_answer("Password reset"))
            else:
                st.markdown(kb_answer("Install software"))
            st.markdown("\nIf you’re still blocked, type **create ticket**.")
        metric_bump("contained", 1)
        st.rerun()

    st.divider()

    # Render history
    for m in st.session_state.messages:
        with st.chat_message(m["role"]):
            st.markdown(m["content"])

    # Chat input
    user_text = st.chat_input("Describe your issue… (e.g., “VPN error 809 on Windows”)")
    if user_text:
        st.session_state.messages.append({"role": "user", "content": user_text})

        lower = user_text.lower().strip()

        # Ticket creation flow (simple command)
        if lower.startswith("create ticket"):
            with st.chat_message("assistant"):
                st.markdown("Let’s file it—two quick picks:")
                urgency = st.radio("Urgency", ["low", "med", "high"], horizontal=True, index=1)
                mood = st.selectbox("How’s your day going?", ["Calm 😌", "Focused 🎯", "Stressed 😵‍💫", "On fire 🔥"], index=1)
                summary = st.text_area("One-line summary (optional)", placeholder="If blank, I’ll use your last message.")
                confirm = st.button("🎫 Create ticket", type="primary", use_container_width=True)

            if confirm:
                # Use last non-command message if summary blank
                last_issue = ""
                for msg in reversed(st.session_state.messages):
                    if msg["role"] == "user" and not msg["content"].lower().strip().startswith("create ticket"):
                        last_issue = msg["content"]
                        break
                seed = summary.strip() if summary.strip() else (last_issue or "General help needed")
                t = create_ticket_from_text(seed, urgency=urgency, mood=mood)
                st.session_state.messages.append(
                    {
                        "role": "assistant",
                        "content": (
                            f"Ticket created: **{t.ticket_id}** 🎉\n\n"
                            f"- Category: **{t.category}**\n"
                            f"- Urgency: **{t.urgency}**\n"
                            f"- Status: **{t.status}**\n\n"
                            "Want to add the exact error text or a screenshot description?"
                        ),
                    }
                )
                st.balloons()
                st.rerun()

        else:
            assistant_typing()
            contained, reply = try_contain(user_text)
            st.session_state.messages.append({"role": "assistant", "content": reply})
            if contained:
                metric_bump("contained", 1)
            st.rerun()
