# Code Generated by Sidekick is for learning and experimentation purposes only.
import re
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import streamlit as st
from sentence_transformers import SentenceTransformer

# ----------------------------
# NLP "model" (embedding-based)
# ----------------------------

INTENTS = ["Login", "VPN", "Wi‑Fi", "Software", "Phishing", "Other"]

INTENT_PROTOTYPES = {
    "Login": [
        "can't sign in", "password reset", "account locked", "MFA not working", "SSO login issue"
    ],
    "VPN": [
        "vpn won't connect", "vpn error code", "remote access issue", "tunnel failed", "client disconnects"
    ],
    "Wi‑Fi": [
        "wifi disconnected", "cannot connect to network", "slow internet", "dns issue", "no internet access"
    ],
    "Software": [
        "app crash", "install failed", "update error", "license issue", "Teams/Outlook not working"
    ],
    "Phishing": [
        "suspicious email", "phishing link", "credential theft", "fake login page", "clicked a suspicious link"
    ],
    "Other": [
        "general IT help", "hardware issue", "printer issue", "how do I", "unknown problem"
    ],
}

KB = [
    {
        "id": "vpn-1",
        "intent": "VPN",
        "title": "VPN connection fails (common checks)",
        "steps": [
            "Confirm internet works (open a few websites).",
            "Restart VPN client and try again.",
            "Switch network (mobile hotspot) to isolate home Wi‑Fi/router issues.",
            "If you see an error code, include it in the ticket.",
            "If still failing, reinstall/update the VPN client."
        ],
    },
    {
        "id": "wifi-1",
        "intent": "Wi‑Fi",
        "title": "Wi‑Fi connected but no internet",
        "steps": [
            "Toggle Wi‑Fi off/on and reconnect.",
            "Forget the network and rejoin.",
            "Restart router/modem.",
            "Try another device on the same network to isolate device vs network.",
            "If corporate network, confirm you’re on the correct SSID/VLAN."
        ],
    },
    {
        "id": "login-1",
        "intent": "Login",
        "title": "Account / login trouble",
        "steps": [
            "Try password reset (if applicable).",
            "Check caps/keyboard layout and try again.",
            "Complete MFA prompt (approve push / enter code).",
            "If locked out, wait the lockout window or request unlock.",
            "If SSO, try private/incognito browser window."
        ],
    },
    {
        "id": "software-1",
        "intent": "Software",
        "title": "Software install or crash issue",
        "steps": [
            "Restart the app (or reboot device if recurring).",
            "Check for updates and install pending patches.",
            "Confirm you have permissions/licensing to install.",
            "Capture the exact error message/screenshot.",
            "If still failing, include app name + version in the ticket."
        ],
    },
    {
        "id": "phish-1",
        "intent": "Phishing",
        "title": "Possible phishing / suspicious email",
        "steps": [
            "Do not click links or open attachments.",
            "Do not reply; report using your org’s phishing-report process.",
            "If you clicked, disconnect from network and change password ASAP.",
            "Capture sender, subject, and any URLs for the ticket.",
            "Monitor for unusual sign-in alerts."
        ],
    },
]

@st.cache_resource
def load_embedder():
    # Lightweight, strong baseline for retrieval + intent classification
    return SentenceTransformer("all-MiniLM-L6-v2")

def _cosine_sim(a: np.ndarray, b: np.ndarray) -> float:
    denom = (np.linalg.norm(a) * np.linalg.norm(b)) + 1e-12
    return float(np.dot(a, b) / denom)

@st.cache_resource
def build_reference_vectors():
    model = load_embedder()

    # Intent vectors = mean of prototype vectors per intent
    intent_vecs = {}
    for intent, protos in INTENT_PROTOTYPES.items():
        vecs = model.encode(protos, normalize_embeddings=True)
        intent_vecs[intent] = np.mean(vecs, axis=0)

    # KB vectors
    kb_texts = []
    for item in KB:
        kb_texts.append(f"{item['intent']} | {item['title']} | " + " ".join(item["steps"]))
    kb_vecs = model.encode(kb_texts, normalize_embeddings=True)

    return intent_vecs, kb_vecs

def predict_intent(text: str):
    text = (text or "").strip()
    if not text:
        return "Other", 0.0

    model = load_embedder()
    intent_vecs, _ = build_reference_vectors()

    q = model.encode([text], normalize_embeddings=True)[0]
    sims = {k: _cosine_sim(q, v) for k, v in intent_vecs.items()}
    best_intent = max(sims, key=sims.get)
    confidence = float(sims[best_intent])

    # If the best match is weak, fall back to Other
    if confidence < 0.35:
        return "Other", confidence
    return best_intent, confidence

def retrieve_kb_item(text: str, intent: str):
    text = (text or "").strip()
    if not text:
        return None, 0.0

    model = load_embedder()
    _, kb_vecs = build_reference_vectors()
    q = model.encode([text], normalize_embeddings=True)[0]

    # Prefer matching-intent items, otherwise use all
    candidate_idxs = [i for i, x in enumerate(KB) if x["intent"] == intent]
    if not candidate_idxs:
        candidate_idxs = list(range(len(KB)))

    best_idx, best_sim = None, -1.0
    for i in candidate_idxs:
        s = _cosine_sim(q, kb_vecs[i])
        if s > best_sim:
            best_idx, best_sim = i, s

    return (KB[best_idx] if best_idx is not None else None), float(best_sim)

def extract_entities(text: str):
    t = (text or "").strip()
    entities = {}

    # OS
    if re.search(r"\bwindows\b", t, re.I):
        entities["os"] = "Windows"
    elif re.search(r"\bmac(os)?\b|\bmacbook\b", t, re.I):
        entities["os"] = "macOS"
    elif re.search(r"\blinux\b|\bubuntu\b", t, re.I):
        entities["os"] = "Linux"
    elif re.search(r"\bios\b|\biphone\b|\bipad\b", t, re.I):
        entities["os"] = "iOS"
    elif re.search(r"\bandroid\b|\bpixel\b|\bsamsung\b", t, re.I):
        entities["os"] = "Android"

    # Error code (3–5 digits), e.g., "error 809"
    m = re.search(r"\b(?:error\s*)?(\d{3,5})\b", t, re.I)
    if m:
        entities["error_code"] = m.group(1)

    # Common apps
    apps = ["Outlook", "Teams", "Excel", "Word", "PowerPoint", "VPN", "Zoom", "Chrome", "Edge"]
    found = [a for a in apps if re.search(rf"\b{re.escape(a)}\b", t, re.I)]
    if found:
        entities["apps"] = ", ".join(found)

    # URLs (phishing signal)
    urls = re.findall(r"https?://\S+|www\.\S+", t, re.I)
    if urls:
        entities["urls"] = ", ".join(urls[:3])

    return entities

# ----------------------------
# Streamlit App
# ----------------------------

st.set_page_config(page_title="Office Helpdesk Buddy (NLP)", layout="wide")
st.title("Office Helpdesk Buddy (NLP Project)")

if "tickets" not in st.session_state:
    st.session_state.tickets = []

tab_help, tab_tickets = st.tabs(["Helpdesk (NLP)", "Tickets"])

with st.sidebar:
    st.subheader("Context (optional)")
    user_name = st.text_input("Name", placeholder="e.g., Asha")
    device = st.text_input("Device", placeholder="e.g., Dell 7420")
    os_user = st.text_input("OS", placeholder="e.g., Windows 11")

with tab_help:
    st.write("Describe the issue; the NLP model will classify intent and suggest steps.")

    c1, c2, c3, c4, c5 = st.columns(5)
    quick = None
    if c1.button("🔐 Login", use_container_width=True):
        quick = "I can't sign in. My MFA isn't working."
    if c2.button("🛡️ VPN", use_container_width=True):
        quick = "VPN won't connect, error 809 on Windows."
    if c3.button("📶 Wi‑Fi", use_container_width=True):
        quick = "Wi‑Fi connects but no internet access."
    if c4.button("🧩 Software", use_container_width=True):
        quick = "Teams keeps crashing after an update."
    if c5.button("🎣 Phishing", use_container_width=True):
        quick = "I got a suspicious email with a login link."

    default_text = quick if quick else ""
    issue = st.text_area(
        "Issue summary",
        value=default_text,
        placeholder="e.g., VPN error 809 on Windows at home Wi‑Fi",
        height=120
    )

    if st.button("Analyze with NLP", type="primary"):
        intent, conf = predict_intent(issue)
        entities = extract_entities(issue)
        kb_item, kb_sim = retrieve_kb_item(issue, intent)

        st.markdown(
            f"**Predicted intent:** `{intent}`  \n"
            f"**Confidence:** `{conf:.2f}`  \n"
            f"**Best KB match:** `{kb_item['title'] if kb_item else 'None'}` (`{kb_sim:.2f}`)"
        )

        if entities:
            st.write("**Extracted details:**")
            st.json(entities)

        if kb_item:
            st.write("**Suggested steps:**")
            for i, step in enumerate(kb_item["steps"], start=1):
                st.write(f"{i}. {step}")
        else:
            st.info("No KB match found. Create a ticket with details.")

    st.divider()
    st.subheader("Create ticket")

    urgency = st.radio("Urgency", ["low", "med", "high"], horizontal=True, index=1)

    if st.button("Create ticket"):
        intent, conf = predict_intent(issue)
        entities = extract_entities(issue)

        ticket = {
            "ticket_id": f"T-{len(st.session_state.tickets)+1:04d}",
            "created_utc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
            "name": user_name.strip() or None,
            "device": device.strip() or None,
            "os": (os_user.strip() or entities.get("os") or None),
            "summary": (issue or "").strip() or "(no summary provided)",
            "predicted_intent": intent,
            "intent_confidence": round(float(conf), 3),
            "urgency": urgency,
            "entities": entities,
            "status": "Open",
        }
        st.session_state.tickets.append(ticket)
        st.success(f"Ticket created: {ticket['ticket_id']}")

with tab_tickets:
    st.subheader("Tickets")
    if not st.session_state.tickets:
        st.info("No tickets yet.")
    else:
        df = pd.DataFrame(st.session_state.tickets)
        st.dataframe(df, use_container_width=True)

        csv = df.to_csv(index=False).encode("utf-8")
        st.download_button(
            "Download tickets (CSV)",
            data=csv,
            file_name="tickets.csv",
            mime="text/csv",
        )

::: follow-ups 
- Add more intents and KB articles
- Show requirements.txt for this NLP app
:::
